# Generated by Django 3.2.21 on 2023-09-27 16:17

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='display_photo',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.room_display_photo_path),
        ),
    ]
